# Generated by Django 4.1 on 2022-08-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(blank=True, max_length=5)),
                ('course', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
