# Generated by Django 4.1 on 2022-09-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_student_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-date_enrolled']},
        ),
    ]
