# Generated by Django 4.1 on 2022-09-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('staff_contact', models.CharField(blank=True, max_length=255)),
                ('place_of_residence', models.CharField(blank=True, max_length=255)),
                ('date_employed', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
