# Generated by Django 4.1 on 2022-09-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_department_alter_staff_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='ssnit_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
