# Generated by Django 4.1 on 2022-09-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_ssnit_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-date_employed']},
        ),
    ]
