# Generated by Django 4.1 on 2022-08-31 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(max_length=5)),
                ('term', models.CharField(max_length=5)),
                ('academic_year', models.CharField(max_length=20)),
                ('total_fees', models.FloatField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('student_class', models.CharField(max_length=20)),
                ('fee_type', models.CharField(max_length=20)),
                ('balance', models.FloatField(max_length=255)),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=5)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('receipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['payment_date'],
            },
        ),
    ]
