# Generated by Django 4.1 on 2022-08-31 20:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipts',
            new_name='Receipt',
        ),
    ]
