# Generated by Django 4.1 on 2022-08-31 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_feescatalogue_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='feescatalogue',
            name='fee_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
