# Generated by Django 4.1 on 2022-09-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_alter_receipt_fee_type_alter_receipt_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='fee_type',
            field=models.CharField(choices=[('BUS', 'BUS'), ('School fees', 'School fees')], max_length=100),
        ),
    ]
