# Generated by Django 4.1 on 2022-09-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_alter_receipt_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount_paid',
            field=models.FloatField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='fee_type',
            field=models.CharField(max_length=20),
        ),
    ]
