# Generated by Django 4.1 on 2022-09-03 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_receipt_amount_paid_alter_receipt_fee_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-payment_date']},
        ),
    ]
