# Generated by Django 4.1 on 2022-09-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_alter_receipt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feescatalogue',
            options={'ordering': ['-academic_year']},
        ),
    ]
