# Generated by Django 4.1 on 2022-09-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_alter_receipt_fee_type_alter_receipt_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feescatalogue',
            name='academic_year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feescatalogue',
            name='student_class',
            field=models.CharField(max_length=50),
        ),
    ]
